name = "GenVariableElimination"
uuid = "43085b26-f70c-46de-9a56-ba379ae2dc52"
authors = [
    "Marco Cusumano-Towner <imarcoam@gmail.com>",
    "Abtin Mogharabin <atbinmogharabin@gmail.com>"
]
version = "0.2.0"

[deps]
FunctionalCollections = "de31a74c-ac4f-5751-b3fd-e18cd04993ca"
Gen = "ea4f424c-a589-11e8-07c0-fd5c91b9da4a"
StatsFuns = "4c63d2b9-4356-54db-8cca-17b64c39e42c"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"

[compat]
julia = "1.9, 1.10, 1.11"
Gen = "0.4"
FunctionalCollections = "0.5"
StatsFuns = "1"
PyCall = "1"

[extras]
Test = "8dfed614-57bb-5bd8-9b06-2694f7f1e7b7"
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"

[targets]
test = ["Test", "BenchmarkTools"]
